### ISSUE TITLE
Unable to bind to other IP address even when using --ip

### ISSUE THREAD

**Issue by doomikus** [Red-Eyed/python_ftp_server#1]
When using the `--ip `option, specifying the IP doesn't then bind to that IP.  The default IP is still used on launching.

**Comment by Red-Eyed** [comment]
Hello, thank you for reporting!
Fixed
Please, check it out

**Comment by doomikus** [comment]
Thanks for fixing Red-Eyed.  Unfortunately, I then learned Crowdstrike blocked the incoming connection but it did listen on the correct IP.
